[rpcServer]
    addr = ":3109"
    timeout = "1s"

[rpcClient]
    dial = "1s"
    timeout = "1s"

[websocket]
    bind = [":9999"]
    keepAlive = false
    readBufferSize = 4096
    writeBufferSize = 4096

[bucket]
    size = 32
    channel = 1024
    room = 1024